project_id = "nwaihnoxcxhtitgagcqk"

[functions.create-payment]
verify_jwt = false

[functions.admin-create-affiliate]
verify_jwt = true

[functions.check-payment-status]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.process-webhook-queue]
verify_jwt = false

[functions.get-upsell-data]
verify_jwt = false

[functions.process-upsell-payment]
verify_jwt = false

[functions.generate-transaction-token]
verify_jwt = false

[functions.track-checkout]
verify_jwt = false

[functions.send-conversion-events]
verify_jwt = true

[functions.track-click]
verify_jwt = false

[functions.track-upsell-event]
verify_jwt = false

[functions.test-webhook]
verify_jwt = true

[functions.send-sale-webhook]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true
