project_id = "vjpbsgqvmgrxohapxukn"

[functions.create-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.process-webhook-queue]
verify_jwt = false

[functions.get-upsell-data]
verify_jwt = false

[functions.process-upsell-payment]
verify_jwt = false

[functions.generate-transaction-token]
verify_jwt = false